---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'stripegirls'
SiteConfig:
  extensions:
    - SiteConfigExtension
SiteConfigExtension:
  facebook_absolute_link: 'http://facebook.com/'
  twitter_absolute_link: 'http://twitter.com/'